# Generated by Django 5.0.6 on 2024-06-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Блог',
                     'verbose_name_plural': 'Блоги'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='count',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
