# Generated by Django 5.0.6 on 2024-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_rename_count_blog_views_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(auto_created='djangodbmodelsfieldscharfield', blank=True, db_index=True, max_length=100, null=True, verbose_name='Слаг'),
        ),
    ]
