# Generated by Django 4.2 on 2024-07-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('content-manager', 'контент-менеджер')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
