# Generated by Django 5.0.6 on 2024-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_manufactured_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название филиала', max_length=100, verbose_name='Название филиала')),
                ('address', models.CharField(help_text='Введите адрес филиала', max_length=100, verbose_name='Адрес филиала')),
                ('phone', models.IntegerField(blank=True, help_text='Введите телефон', null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
