# Generated by Django 5.0.6 on 2024-06-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефон',
                                   max_length=100, null=True,
                                   verbose_name='Телефон'),
        ),
    ]
