# Generated by Django 5.0.6 on 2024-07-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_contacts_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(help_text='Введите версию', verbose_name='Версия')),
                ('title', models.CharField(help_text='Введите название версии', max_length=100, verbose_name='Название версии')),
                ('current_version', models.BooleanField(default=False, help_text='Это текущая версия?', verbose_name='Текущая версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='catalog.product', verbose_name='Продукт')),
            ],
        ),
    ]
